# Generated by Django 2.1.8 on 2019-11-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcity7dforecast',
            name='mr',
            field=models.CharField(default='', max_length=8, verbose_name='月出时间'),
        ),
        migrations.AlterField(
            model_name='wcity7dforecast',
            name='ms',
            field=models.CharField(default='', max_length=8, verbose_name='月升时间'),
        ),
        migrations.AlterField(
            model_name='wcity7dforecast',
            name='sr',
            field=models.CharField(default='', max_length=8, verbose_name='日出时间'),
        ),
        migrations.AlterField(
            model_name='wcity7dforecast',
            name='ss',
            field=models.CharField(default='', max_length=8, verbose_name='日落时间'),
        ),
    ]
