# Generated by Django 2.1.8 on 2019-11-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsurl', models.CharField(max_length=256, verbose_name='链接')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('categoryid', models.CharField(max_length=256, verbose_name='分类')),
                ('time', models.CharField(max_length=64, verbose_name='新闻时间')),
                ('source', models.CharField(max_length=64, verbose_name='来源网站')),
                ('tag', models.CharField(max_length=64, verbose_name='新闻标签')),
                ('context', models.TextField(verbose_name='正文')),
                ('imgurl', models.CharField(max_length=512, verbose_name='图片链接')),
                ('part', models.TextField(verbose_name='正文代码块')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='NewsFinger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.CharField(max_length=32, verbose_name='指纹')),
            ],
        ),
        migrations.CreateModel(
            name='sevendaysweather',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('datatime', models.CharField(max_length=12, verbose_name='时间')),
                ('day01', models.CharField(max_length=50)),
                ('day02', models.CharField(max_length=50)),
                ('day03', models.CharField(max_length=50)),
                ('day04', models.CharField(max_length=50)),
                ('day05', models.CharField(max_length=50)),
                ('day06', models.CharField(max_length=50)),
                ('day07', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsurl', models.CharField(max_length=256, verbose_name='链接')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('categoryid', models.CharField(max_length=256, verbose_name='分类')),
                ('time', models.CharField(max_length=64, verbose_name='新闻时z间')),
                ('source', models.CharField(max_length=64, verbose_name='来源网站')),
                ('tag', models.CharField(max_length=64, verbose_name='新闻标签')),
                ('context', models.TextField(verbose_name='正文')),
                ('imgurl', models.CharField(max_length=512, verbose_name='图片链接')),
                ('part', models.TextField(verbose_name='正文代码块')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsurl', models.CharField(max_length=256, verbose_name='链接')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('categoryid', models.CharField(max_length=256, verbose_name='分类')),
                ('time', models.CharField(max_length=64, verbose_name='新闻时间')),
                ('source', models.CharField(max_length=64, verbose_name='来源网站')),
                ('tag', models.CharField(max_length=64, verbose_name='新闻标签')),
                ('context', models.TextField(verbose_name='正文')),
                ('imgurl', models.CharField(max_length=512, verbose_name='图片链接')),
                ('part', models.TextField(verbose_name='正文代码块')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsurl', models.CharField(max_length=256, verbose_name='链接')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('categoryid', models.CharField(max_length=256, verbose_name='分类')),
                ('time', models.CharField(max_length=64, verbose_name='新闻时间')),
                ('source', models.CharField(max_length=64, verbose_name='来源网站')),
                ('tag', models.CharField(max_length=64, verbose_name='新闻标签')),
                ('context', models.TextField(verbose_name='正文')),
                ('imgurl', models.CharField(max_length=512, verbose_name='图片链接')),
                ('part', models.TextField(verbose_name='正文代码块')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
            ],
        ),
        migrations.DeleteModel(
            name='FutureWeather',
        ),
        migrations.DeleteModel(
            name='RealtimeWeather',
        ),
        migrations.DeleteModel(
            name='TodayWeather',
        ),
        migrations.AlterUniqueTogether(
            name='sevendaysweather',
            unique_together={('name', 'datatime')},
        ),
    ]
