# Generated by Django 2.1.8 on 2019-11-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191125_2122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.AlterModelTable(
            name='newsfinger',
            table='news_finger',
        ),
        migrations.AlterModelTable(
            name='specialnews',
            table='special_news',
        ),
        migrations.AlterModelTable(
            name='traffic',
            table='traffic',
        ),
        migrations.AlterModelTable(
            name='weather',
            table='weather',
        ),
    ]
