# Generated by Django 2.1.8 on 2019-11-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191125_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='SevendaysWeatherImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='景点名称')),
                ('imgurl', models.CharField(max_length=256, verbose_name='图片路径')),
            ],
            options={
                'db_table': 'sevendaysweatherimage',
            },
        ),
        migrations.AlterModelTable(
            name='sevendaysweather',
            table='sevendaysweather',
        ),
    ]
