# Generated by Django 2.1.8 on 2019-11-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191129_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='TjNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsurl', models.CharField(max_length=256, verbose_name='链接')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('categoryid', models.CharField(max_length=256, verbose_name='分类')),
                ('time', models.CharField(max_length=64, verbose_name='新闻时间')),
                ('source', models.CharField(max_length=64, verbose_name='来源网站')),
                ('tag', models.CharField(max_length=64, verbose_name='新闻标签')),
                ('content', models.TextField(verbose_name='正文')),
                ('imgurl', models.CharField(max_length=512, verbose_name='图片链接')),
                ('part', models.TextField(verbose_name='正文代码块')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
            ],
            options={
                'db_table': 'tjnews',
            },
        ),
        migrations.CreateModel(
            name='TravelNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsurl', models.CharField(max_length=256, verbose_name='链接')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('categoryid', models.CharField(max_length=256, verbose_name='分类')),
                ('time', models.CharField(max_length=64, verbose_name='新闻时间')),
                ('source', models.CharField(max_length=64, verbose_name='来源网站')),
                ('tag', models.CharField(max_length=64, verbose_name='新闻标签')),
                ('content', models.TextField(verbose_name='正文')),
                ('imgurl', models.CharField(max_length=512, verbose_name='图片链接')),
                ('part', models.TextField(verbose_name='正文代码块')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
            ],
            options={
                'db_table': 'travelnews',
            },
        ),
    ]
